# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\jenik\coding\herni_konzole\game_console_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\jenik\coding\herni_konzole\game_console_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\jenik\coding\herni_konzole\game_console_project\CMakeFiles C:\jenik\coding\herni_konzole\game_console_project\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\jenik\coding\herni_konzole\game_console_project\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game_console

# Build rule for target.
game_console: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 game_console
.PHONY : game_console

# fast build rule for target.
game_console/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/build
.PHONY : game_console/fast

libs/ArduinoCore-API/api/Common.obj: libs/ArduinoCore-API/api/Common.cpp.obj
.PHONY : libs/ArduinoCore-API/api/Common.obj

# target to build an object file
libs/ArduinoCore-API/api/Common.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/Common.cpp.obj
.PHONY : libs/ArduinoCore-API/api/Common.cpp.obj

libs/ArduinoCore-API/api/Common.i: libs/ArduinoCore-API/api/Common.cpp.i
.PHONY : libs/ArduinoCore-API/api/Common.i

# target to preprocess a source file
libs/ArduinoCore-API/api/Common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/Common.cpp.i
.PHONY : libs/ArduinoCore-API/api/Common.cpp.i

libs/ArduinoCore-API/api/Common.s: libs/ArduinoCore-API/api/Common.cpp.s
.PHONY : libs/ArduinoCore-API/api/Common.s

# target to generate assembly for a file
libs/ArduinoCore-API/api/Common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/Common.cpp.s
.PHONY : libs/ArduinoCore-API/api/Common.cpp.s

libs/ArduinoCore-API/api/IPAddress.obj: libs/ArduinoCore-API/api/IPAddress.cpp.obj
.PHONY : libs/ArduinoCore-API/api/IPAddress.obj

# target to build an object file
libs/ArduinoCore-API/api/IPAddress.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/IPAddress.cpp.obj
.PHONY : libs/ArduinoCore-API/api/IPAddress.cpp.obj

libs/ArduinoCore-API/api/IPAddress.i: libs/ArduinoCore-API/api/IPAddress.cpp.i
.PHONY : libs/ArduinoCore-API/api/IPAddress.i

# target to preprocess a source file
libs/ArduinoCore-API/api/IPAddress.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/IPAddress.cpp.i
.PHONY : libs/ArduinoCore-API/api/IPAddress.cpp.i

libs/ArduinoCore-API/api/IPAddress.s: libs/ArduinoCore-API/api/IPAddress.cpp.s
.PHONY : libs/ArduinoCore-API/api/IPAddress.s

# target to generate assembly for a file
libs/ArduinoCore-API/api/IPAddress.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/IPAddress.cpp.s
.PHONY : libs/ArduinoCore-API/api/IPAddress.cpp.s

libs/ArduinoCore-API/api/Print.obj: libs/ArduinoCore-API/api/Print.cpp.obj
.PHONY : libs/ArduinoCore-API/api/Print.obj

# target to build an object file
libs/ArduinoCore-API/api/Print.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/Print.cpp.obj
.PHONY : libs/ArduinoCore-API/api/Print.cpp.obj

libs/ArduinoCore-API/api/Print.i: libs/ArduinoCore-API/api/Print.cpp.i
.PHONY : libs/ArduinoCore-API/api/Print.i

# target to preprocess a source file
libs/ArduinoCore-API/api/Print.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/Print.cpp.i
.PHONY : libs/ArduinoCore-API/api/Print.cpp.i

libs/ArduinoCore-API/api/Print.s: libs/ArduinoCore-API/api/Print.cpp.s
.PHONY : libs/ArduinoCore-API/api/Print.s

# target to generate assembly for a file
libs/ArduinoCore-API/api/Print.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/Print.cpp.s
.PHONY : libs/ArduinoCore-API/api/Print.cpp.s

libs/ArduinoCore-API/api/Stream.obj: libs/ArduinoCore-API/api/Stream.cpp.obj
.PHONY : libs/ArduinoCore-API/api/Stream.obj

# target to build an object file
libs/ArduinoCore-API/api/Stream.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/Stream.cpp.obj
.PHONY : libs/ArduinoCore-API/api/Stream.cpp.obj

libs/ArduinoCore-API/api/Stream.i: libs/ArduinoCore-API/api/Stream.cpp.i
.PHONY : libs/ArduinoCore-API/api/Stream.i

# target to preprocess a source file
libs/ArduinoCore-API/api/Stream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/Stream.cpp.i
.PHONY : libs/ArduinoCore-API/api/Stream.cpp.i

libs/ArduinoCore-API/api/Stream.s: libs/ArduinoCore-API/api/Stream.cpp.s
.PHONY : libs/ArduinoCore-API/api/Stream.s

# target to generate assembly for a file
libs/ArduinoCore-API/api/Stream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/Stream.cpp.s
.PHONY : libs/ArduinoCore-API/api/Stream.cpp.s

libs/ArduinoCore-API/api/String.obj: libs/ArduinoCore-API/api/String.cpp.obj
.PHONY : libs/ArduinoCore-API/api/String.obj

# target to build an object file
libs/ArduinoCore-API/api/String.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/String.cpp.obj
.PHONY : libs/ArduinoCore-API/api/String.cpp.obj

libs/ArduinoCore-API/api/String.i: libs/ArduinoCore-API/api/String.cpp.i
.PHONY : libs/ArduinoCore-API/api/String.i

# target to preprocess a source file
libs/ArduinoCore-API/api/String.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/String.cpp.i
.PHONY : libs/ArduinoCore-API/api/String.cpp.i

libs/ArduinoCore-API/api/String.s: libs/ArduinoCore-API/api/String.cpp.s
.PHONY : libs/ArduinoCore-API/api/String.s

# target to generate assembly for a file
libs/ArduinoCore-API/api/String.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/api/String.cpp.s
.PHONY : libs/ArduinoCore-API/api/String.cpp.s

libs/ArduinoCore-API/test/src/MillisFake.obj: libs/ArduinoCore-API/test/src/MillisFake.cpp.obj
.PHONY : libs/ArduinoCore-API/test/src/MillisFake.obj

# target to build an object file
libs/ArduinoCore-API/test/src/MillisFake.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/test/src/MillisFake.cpp.obj
.PHONY : libs/ArduinoCore-API/test/src/MillisFake.cpp.obj

libs/ArduinoCore-API/test/src/MillisFake.i: libs/ArduinoCore-API/test/src/MillisFake.cpp.i
.PHONY : libs/ArduinoCore-API/test/src/MillisFake.i

# target to preprocess a source file
libs/ArduinoCore-API/test/src/MillisFake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/test/src/MillisFake.cpp.i
.PHONY : libs/ArduinoCore-API/test/src/MillisFake.cpp.i

libs/ArduinoCore-API/test/src/MillisFake.s: libs/ArduinoCore-API/test/src/MillisFake.cpp.s
.PHONY : libs/ArduinoCore-API/test/src/MillisFake.s

# target to generate assembly for a file
libs/ArduinoCore-API/test/src/MillisFake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/test/src/MillisFake.cpp.s
.PHONY : libs/ArduinoCore-API/test/src/MillisFake.cpp.s

libs/ArduinoCore-API/test/src/dtostrf.obj: libs/ArduinoCore-API/test/src/dtostrf.cpp.obj
.PHONY : libs/ArduinoCore-API/test/src/dtostrf.obj

# target to build an object file
libs/ArduinoCore-API/test/src/dtostrf.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/test/src/dtostrf.cpp.obj
.PHONY : libs/ArduinoCore-API/test/src/dtostrf.cpp.obj

libs/ArduinoCore-API/test/src/dtostrf.i: libs/ArduinoCore-API/test/src/dtostrf.cpp.i
.PHONY : libs/ArduinoCore-API/test/src/dtostrf.i

# target to preprocess a source file
libs/ArduinoCore-API/test/src/dtostrf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/test/src/dtostrf.cpp.i
.PHONY : libs/ArduinoCore-API/test/src/dtostrf.cpp.i

libs/ArduinoCore-API/test/src/dtostrf.s: libs/ArduinoCore-API/test/src/dtostrf.cpp.s
.PHONY : libs/ArduinoCore-API/test/src/dtostrf.s

# target to generate assembly for a file
libs/ArduinoCore-API/test/src/dtostrf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/test/src/dtostrf.cpp.s
.PHONY : libs/ArduinoCore-API/test/src/dtostrf.cpp.s

libs/ArduinoCore-API/test/src/itoa.obj: libs/ArduinoCore-API/test/src/itoa.cpp.obj
.PHONY : libs/ArduinoCore-API/test/src/itoa.obj

# target to build an object file
libs/ArduinoCore-API/test/src/itoa.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/test/src/itoa.cpp.obj
.PHONY : libs/ArduinoCore-API/test/src/itoa.cpp.obj

libs/ArduinoCore-API/test/src/itoa.i: libs/ArduinoCore-API/test/src/itoa.cpp.i
.PHONY : libs/ArduinoCore-API/test/src/itoa.i

# target to preprocess a source file
libs/ArduinoCore-API/test/src/itoa.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/test/src/itoa.cpp.i
.PHONY : libs/ArduinoCore-API/test/src/itoa.cpp.i

libs/ArduinoCore-API/test/src/itoa.s: libs/ArduinoCore-API/test/src/itoa.cpp.s
.PHONY : libs/ArduinoCore-API/test/src/itoa.s

# target to generate assembly for a file
libs/ArduinoCore-API/test/src/itoa.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/ArduinoCore-API/test/src/itoa.cpp.s
.PHONY : libs/ArduinoCore-API/test/src/itoa.cpp.s

libs/adafruit_driver/Adafruit_GFX.obj: libs/adafruit_driver/Adafruit_GFX.cpp.obj
.PHONY : libs/adafruit_driver/Adafruit_GFX.obj

# target to build an object file
libs/adafruit_driver/Adafruit_GFX.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/adafruit_driver/Adafruit_GFX.cpp.obj
.PHONY : libs/adafruit_driver/Adafruit_GFX.cpp.obj

libs/adafruit_driver/Adafruit_GFX.i: libs/adafruit_driver/Adafruit_GFX.cpp.i
.PHONY : libs/adafruit_driver/Adafruit_GFX.i

# target to preprocess a source file
libs/adafruit_driver/Adafruit_GFX.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/adafruit_driver/Adafruit_GFX.cpp.i
.PHONY : libs/adafruit_driver/Adafruit_GFX.cpp.i

libs/adafruit_driver/Adafruit_GFX.s: libs/adafruit_driver/Adafruit_GFX.cpp.s
.PHONY : libs/adafruit_driver/Adafruit_GFX.s

# target to generate assembly for a file
libs/adafruit_driver/Adafruit_GFX.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/adafruit_driver/Adafruit_GFX.cpp.s
.PHONY : libs/adafruit_driver/Adafruit_GFX.cpp.s

libs/adafruit_driver/Adafruit_PCD8544.obj: libs/adafruit_driver/Adafruit_PCD8544.cpp.obj
.PHONY : libs/adafruit_driver/Adafruit_PCD8544.obj

# target to build an object file
libs/adafruit_driver/Adafruit_PCD8544.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/adafruit_driver/Adafruit_PCD8544.cpp.obj
.PHONY : libs/adafruit_driver/Adafruit_PCD8544.cpp.obj

libs/adafruit_driver/Adafruit_PCD8544.i: libs/adafruit_driver/Adafruit_PCD8544.cpp.i
.PHONY : libs/adafruit_driver/Adafruit_PCD8544.i

# target to preprocess a source file
libs/adafruit_driver/Adafruit_PCD8544.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/adafruit_driver/Adafruit_PCD8544.cpp.i
.PHONY : libs/adafruit_driver/Adafruit_PCD8544.cpp.i

libs/adafruit_driver/Adafruit_PCD8544.s: libs/adafruit_driver/Adafruit_PCD8544.cpp.s
.PHONY : libs/adafruit_driver/Adafruit_PCD8544.s

# target to generate assembly for a file
libs/adafruit_driver/Adafruit_PCD8544.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/libs/adafruit_driver/Adafruit_PCD8544.cpp.s
.PHONY : libs/adafruit_driver/Adafruit_PCD8544.cpp.s

src/Buttons.obj: src/Buttons.cpp.obj
.PHONY : src/Buttons.obj

# target to build an object file
src/Buttons.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/Buttons.cpp.obj
.PHONY : src/Buttons.cpp.obj

src/Buttons.i: src/Buttons.cpp.i
.PHONY : src/Buttons.i

# target to preprocess a source file
src/Buttons.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/Buttons.cpp.i
.PHONY : src/Buttons.cpp.i

src/Buttons.s: src/Buttons.cpp.s
.PHONY : src/Buttons.s

# target to generate assembly for a file
src/Buttons.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/Buttons.cpp.s
.PHONY : src/Buttons.cpp.s

src/game_execution.obj: src/game_execution.cpp.obj
.PHONY : src/game_execution.obj

# target to build an object file
src/game_execution.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/game_execution.cpp.obj
.PHONY : src/game_execution.cpp.obj

src/game_execution.i: src/game_execution.cpp.i
.PHONY : src/game_execution.i

# target to preprocess a source file
src/game_execution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/game_execution.cpp.i
.PHONY : src/game_execution.cpp.i

src/game_execution.s: src/game_execution.cpp.s
.PHONY : src/game_execution.s

# target to generate assembly for a file
src/game_execution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/game_execution.cpp.s
.PHONY : src/game_execution.cpp.s

src/games/space_game/space_game.obj: src/games/space_game/space_game.cpp.obj
.PHONY : src/games/space_game/space_game.obj

# target to build an object file
src/games/space_game/space_game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/games/space_game/space_game.cpp.obj
.PHONY : src/games/space_game/space_game.cpp.obj

src/games/space_game/space_game.i: src/games/space_game/space_game.cpp.i
.PHONY : src/games/space_game/space_game.i

# target to preprocess a source file
src/games/space_game/space_game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/games/space_game/space_game.cpp.i
.PHONY : src/games/space_game/space_game.cpp.i

src/games/space_game/space_game.s: src/games/space_game/space_game.cpp.s
.PHONY : src/games/space_game/space_game.s

# target to generate assembly for a file
src/games/space_game/space_game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/games/space_game/space_game.cpp.s
.PHONY : src/games/space_game/space_game.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/main_menu.obj: src/main_menu.cpp.obj
.PHONY : src/main_menu.obj

# target to build an object file
src/main_menu.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/main_menu.cpp.obj
.PHONY : src/main_menu.cpp.obj

src/main_menu.i: src/main_menu.cpp.i
.PHONY : src/main_menu.i

# target to preprocess a source file
src/main_menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/main_menu.cpp.i
.PHONY : src/main_menu.cpp.i

src/main_menu.s: src/main_menu.cpp.s
.PHONY : src/main_menu.s

# target to generate assembly for a file
src/main_menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/main_menu.cpp.s
.PHONY : src/main_menu.cpp.s

src/menu/analog_voltage_demo.obj: src/menu/analog_voltage_demo.cpp.obj
.PHONY : src/menu/analog_voltage_demo.obj

# target to build an object file
src/menu/analog_voltage_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/menu/analog_voltage_demo.cpp.obj
.PHONY : src/menu/analog_voltage_demo.cpp.obj

src/menu/analog_voltage_demo.i: src/menu/analog_voltage_demo.cpp.i
.PHONY : src/menu/analog_voltage_demo.i

# target to preprocess a source file
src/menu/analog_voltage_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/menu/analog_voltage_demo.cpp.i
.PHONY : src/menu/analog_voltage_demo.cpp.i

src/menu/analog_voltage_demo.s: src/menu/analog_voltage_demo.cpp.s
.PHONY : src/menu/analog_voltage_demo.s

# target to generate assembly for a file
src/menu/analog_voltage_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/menu/analog_voltage_demo.cpp.s
.PHONY : src/menu/analog_voltage_demo.cpp.s

src/menu/keyboard.obj: src/menu/keyboard.cpp.obj
.PHONY : src/menu/keyboard.obj

# target to build an object file
src/menu/keyboard.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/menu/keyboard.cpp.obj
.PHONY : src/menu/keyboard.cpp.obj

src/menu/keyboard.i: src/menu/keyboard.cpp.i
.PHONY : src/menu/keyboard.i

# target to preprocess a source file
src/menu/keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/menu/keyboard.cpp.i
.PHONY : src/menu/keyboard.cpp.i

src/menu/keyboard.s: src/menu/keyboard.cpp.s
.PHONY : src/menu/keyboard.s

# target to generate assembly for a file
src/menu/keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/menu/keyboard.cpp.s
.PHONY : src/menu/keyboard.cpp.s

src/menu/menu_item.obj: src/menu/menu_item.cpp.obj
.PHONY : src/menu/menu_item.obj

# target to build an object file
src/menu/menu_item.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/menu/menu_item.cpp.obj
.PHONY : src/menu/menu_item.cpp.obj

src/menu/menu_item.i: src/menu/menu_item.cpp.i
.PHONY : src/menu/menu_item.i

# target to preprocess a source file
src/menu/menu_item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/menu/menu_item.cpp.i
.PHONY : src/menu/menu_item.cpp.i

src/menu/menu_item.s: src/menu/menu_item.cpp.s
.PHONY : src/menu/menu_item.s

# target to generate assembly for a file
src/menu/menu_item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/menu/menu_item.cpp.s
.PHONY : src/menu/menu_item.cpp.s

src/wifi/remote_sw_update.obj: src/wifi/remote_sw_update.cpp.obj
.PHONY : src/wifi/remote_sw_update.obj

# target to build an object file
src/wifi/remote_sw_update.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/wifi/remote_sw_update.cpp.obj
.PHONY : src/wifi/remote_sw_update.cpp.obj

src/wifi/remote_sw_update.i: src/wifi/remote_sw_update.cpp.i
.PHONY : src/wifi/remote_sw_update.i

# target to preprocess a source file
src/wifi/remote_sw_update.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/wifi/remote_sw_update.cpp.i
.PHONY : src/wifi/remote_sw_update.cpp.i

src/wifi/remote_sw_update.s: src/wifi/remote_sw_update.cpp.s
.PHONY : src/wifi/remote_sw_update.s

# target to generate assembly for a file
src/wifi/remote_sw_update.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/wifi/remote_sw_update.cpp.s
.PHONY : src/wifi/remote_sw_update.cpp.s

src/wifi/wifi_features.obj: src/wifi/wifi_features.cpp.obj
.PHONY : src/wifi/wifi_features.obj

# target to build an object file
src/wifi/wifi_features.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/wifi/wifi_features.cpp.obj
.PHONY : src/wifi/wifi_features.cpp.obj

src/wifi/wifi_features.i: src/wifi/wifi_features.cpp.i
.PHONY : src/wifi/wifi_features.i

# target to preprocess a source file
src/wifi/wifi_features.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/wifi/wifi_features.cpp.i
.PHONY : src/wifi/wifi_features.cpp.i

src/wifi/wifi_features.s: src/wifi/wifi_features.cpp.s
.PHONY : src/wifi/wifi_features.s

# target to generate assembly for a file
src/wifi/wifi_features.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/wifi/wifi_features.cpp.s
.PHONY : src/wifi/wifi_features.cpp.s

src/x86/ArduinoCore-x86.obj: src/x86/ArduinoCore-x86.cpp.obj
.PHONY : src/x86/ArduinoCore-x86.obj

# target to build an object file
src/x86/ArduinoCore-x86.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/x86/ArduinoCore-x86.cpp.obj
.PHONY : src/x86/ArduinoCore-x86.cpp.obj

src/x86/ArduinoCore-x86.i: src/x86/ArduinoCore-x86.cpp.i
.PHONY : src/x86/ArduinoCore-x86.i

# target to preprocess a source file
src/x86/ArduinoCore-x86.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/x86/ArduinoCore-x86.cpp.i
.PHONY : src/x86/ArduinoCore-x86.cpp.i

src/x86/ArduinoCore-x86.s: src/x86/ArduinoCore-x86.cpp.s
.PHONY : src/x86/ArduinoCore-x86.s

# target to generate assembly for a file
src/x86/ArduinoCore-x86.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\game_console.dir\build.make CMakeFiles/game_console.dir/src/x86/ArduinoCore-x86.cpp.s
.PHONY : src/x86/ArduinoCore-x86.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... game_console
	@echo ... libs/ArduinoCore-API/api/Common.obj
	@echo ... libs/ArduinoCore-API/api/Common.i
	@echo ... libs/ArduinoCore-API/api/Common.s
	@echo ... libs/ArduinoCore-API/api/IPAddress.obj
	@echo ... libs/ArduinoCore-API/api/IPAddress.i
	@echo ... libs/ArduinoCore-API/api/IPAddress.s
	@echo ... libs/ArduinoCore-API/api/Print.obj
	@echo ... libs/ArduinoCore-API/api/Print.i
	@echo ... libs/ArduinoCore-API/api/Print.s
	@echo ... libs/ArduinoCore-API/api/Stream.obj
	@echo ... libs/ArduinoCore-API/api/Stream.i
	@echo ... libs/ArduinoCore-API/api/Stream.s
	@echo ... libs/ArduinoCore-API/api/String.obj
	@echo ... libs/ArduinoCore-API/api/String.i
	@echo ... libs/ArduinoCore-API/api/String.s
	@echo ... libs/ArduinoCore-API/test/src/MillisFake.obj
	@echo ... libs/ArduinoCore-API/test/src/MillisFake.i
	@echo ... libs/ArduinoCore-API/test/src/MillisFake.s
	@echo ... libs/ArduinoCore-API/test/src/dtostrf.obj
	@echo ... libs/ArduinoCore-API/test/src/dtostrf.i
	@echo ... libs/ArduinoCore-API/test/src/dtostrf.s
	@echo ... libs/ArduinoCore-API/test/src/itoa.obj
	@echo ... libs/ArduinoCore-API/test/src/itoa.i
	@echo ... libs/ArduinoCore-API/test/src/itoa.s
	@echo ... libs/adafruit_driver/Adafruit_GFX.obj
	@echo ... libs/adafruit_driver/Adafruit_GFX.i
	@echo ... libs/adafruit_driver/Adafruit_GFX.s
	@echo ... libs/adafruit_driver/Adafruit_PCD8544.obj
	@echo ... libs/adafruit_driver/Adafruit_PCD8544.i
	@echo ... libs/adafruit_driver/Adafruit_PCD8544.s
	@echo ... src/Buttons.obj
	@echo ... src/Buttons.i
	@echo ... src/Buttons.s
	@echo ... src/game_execution.obj
	@echo ... src/game_execution.i
	@echo ... src/game_execution.s
	@echo ... src/games/space_game/space_game.obj
	@echo ... src/games/space_game/space_game.i
	@echo ... src/games/space_game/space_game.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/main_menu.obj
	@echo ... src/main_menu.i
	@echo ... src/main_menu.s
	@echo ... src/menu/analog_voltage_demo.obj
	@echo ... src/menu/analog_voltage_demo.i
	@echo ... src/menu/analog_voltage_demo.s
	@echo ... src/menu/keyboard.obj
	@echo ... src/menu/keyboard.i
	@echo ... src/menu/keyboard.s
	@echo ... src/menu/menu_item.obj
	@echo ... src/menu/menu_item.i
	@echo ... src/menu/menu_item.s
	@echo ... src/wifi/remote_sw_update.obj
	@echo ... src/wifi/remote_sw_update.i
	@echo ... src/wifi/remote_sw_update.s
	@echo ... src/wifi/wifi_features.obj
	@echo ... src/wifi/wifi_features.i
	@echo ... src/wifi/wifi_features.s
	@echo ... src/x86/ArduinoCore-x86.obj
	@echo ... src/x86/ArduinoCore-x86.i
	@echo ... src/x86/ArduinoCore-x86.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

